name = "blog-api"
main = "src/worker.js"
compatibility_date = "2024-01-06"
workers_dev = true
node_compat = true
kv_namespaces = [
    { binding = "bloglikes", id = "a8022ccb356440b0bb790f467feda8f7" }
]
